config/routes.rb
Rails.application.routes.draw do

  resources :brands, except: [:show, :destroy]
  resources :categories, except: [:show, :destroy]
  resources :uoms, except: [:show, :destroy]
  resources :products, except: [:show, :destroy]
  resources :purchases
  resources :sales
  root "home#index"
end

app/models/brand.rb
class Brand < ApplicationRecord

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :active, inclusion: { in: [ true, false ] }

  scope :active_brands, ->{ where(active: true) }
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  before_action :find_brand, only: [:edit, :update]

  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      flash[:success] = "Brand created successfully"
      redirect_to brands_path
    else
      flash.now[:danger] = "Error while creating Brand"
      render "new"
    end
  end

  def edit
  end

  def update
    if @brand.update(brand_params)
      flash[:success] = "Brand edited successfully"
      redirect_to brands_path
    else
      flash.now[:danger] = "Error while editing Brand"
      render "edit"
    end
  end


  private

  def brand_params
    params.require(:brand).permit(:name, :active)
  end

  def find_brand
    @brand = Brand.find(params[:id])
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_brands_form.html.erb
<%= form_for @brand, html: {class: "form-horizontal-center"} do |f| %>

  <% if @brand.errors.any? %>
    <% count = 1%>
    <% @brand.errors.full_messages.each do |msg| %>
      <p class="text-danger"><%= count%>. <%= msg %></p>
      <% count +=1 %>
    <% end %>
  <%end%>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Enter Brand Name", required: true, class: "form-control" %>
  </p>
  <p>
    <%= f.label :active, "Active" %>
    <%= f.select :active, ["true", "false"], { required: true },  class: "form-control" %>
  </p>
  <p>
    <%= f.submit class: "btn btn-success btn-sm", disabled_with: "Saving" %>
  </p>

<% end %>

app/views/brands/edit.html.erb
<h1 class="text-center mb-5 mt-3">Edit Brand</h1>

<div class="row justify-content-center">
  <div class="col-3">
    <%= render "brands_form" %>
  </div>
</div>

app/views/brands/index.html.erb
<div class="mb-4 mt-2 clearfix">
  <h1 class="d-inline-block mb-0">Brands</h1>
  <%= link_to '<i class="fa fa-plus"></i> Add new brand'.html_safe, new_brand_path, class: "pull-right" %>
</div>
<table class="table table-striped ml-auto mr-auto text-center">
  <thead>
    <tr class="thead-dark">
      <th scope="col">S.No</th>
      <th scope="col">Name</th>
      <th scope="col">Active</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
    <% serial_number = 1 %>
    <% @brands.each do |brand| %>
      <tr>
        <th scope="row"><%= serial_number %></th>
        <td><%= brand.name %></td>
        <td><%= brand.active %></</td>
        <td><%= link_to ('<i class="fa fa-edit "></i>').html_safe, edit_brand_path(brand) %></td>
      </tr>
      <% serial_number += 1%>
    <% end %>
  </tbody>
</table>

app/views/brands/new.html.erb
<h1 class="text-center mb-5">New Brand</h1>

<div class="row justify-content-center">
  <div class="col-3">
    <%= render "brands_form" %>
  </div>
</div>