config/routes.rb
Rails.application.routes.draw do

  resources :brands, except: [:show, :destroy]
  resources :categories, except: [:show, :destroy]
  resources :uoms, except: [:show, :destroy]
  resources :products, except: [:show, :destroy]
  resources :purchases
  resources :sales
  root "home#index"
end

app/models/category.rb
class Category < ApplicationRecord

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :active, inclusion: { in: [ true, false ] }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :find_category, only: [:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = "Category created successfully"
      redirect_to categories_path
    else
      flash.now[:danger] = "Error while creating Category"
      render "new"
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category edited successfully"
      redirect_to categories_path
    else
      flash.now[:danger] = "Error while editing Category"
      render "edit"
    end
  end


  private

  def category_params
    params.require(:category).permit(:name, :active)
  end

  def find_category
    @category = Category.find(params[:id])
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories_form.html.erb
<%= form_for @category, class: "form-group" do |f| %>

  <% if @category.errors.any? %>
    <% count = 1%>
    <% @category.errors.full_messages.each do |msg| %>
      <p class="text-danger"><%= count%>. <%= msg %></p>
      <% count += 1 %>
    <% end %>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Enter Category Name", required: true, class: "form-control" %>
  </p>
  <p>
    <%= f.label :active, "Active" %>
    <%= f.select :active, ["true", "false"], { required: true }, class: "form-control" %>
  </p>
  <p>
    <%= f.submit class: "btn btn-success btn-sm", disabled_with: "Saving" %>
  </p>

<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mb-5 mt-3">Edit Category</h1>

<div class="row justify-content-center">
  <div class="col-3">
    <%= render "categories_form" %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="mb-4 mt-2 clearfix">
  <h1 class="d-inline-block mb-0">Categories</h1>
  <%= link_to '<i class="fa fa-plus"></i> Add new category'.html_safe, new_category_path, class: "pull-right" %>
</div>
<table class="table table-striped ml-auto mr-auto text-center">
  <thead>
    <tr class="thead-dark">
      <th scope="col">S.No</th>
      <th scope="col">Name</th>
      <th scope="col">Active</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
    <% serial_number = 1 %>
    <% @categories.each do |category| %>
      <tr>
        <th scope="row"><%= serial_number %></th>
        <td><%= category.name %></td>
        <td><%= category.active %></</td>
        <td><%= link_to ('<i class="fa fa-edit "></i>').html_safe, edit_category_path(category) %></td>
      </tr>
      <% serial_number += 1%>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1 class="text-center mb-5 mt-3">New Category</h1>

<div class="row justify-content-center">
  <div class="col-3">
    <%= render "categories_form" %>
  </div>
</div>