config/routes.rb
Rails.application.routes.draw do

  resources :brands, except: [:show, :destroy]
  resources :categories, except: [:show, :destroy]
  resources :uoms, except: [:show, :destroy]
  resources :products, except: [:show, :destroy]
  resources :purchases
  resources :sales
  root "home#index"
end

app/models/sale.rb
class Sale < ApplicationRecord
  has_many :sale_items, dependent: :destroy
  accepts_nested_attributes_for :sale_items, reject_if: :all_blank, allow_destroy: true

  scope :order_by_sale_date, -> { order(date: :desc, id: :desc) }

  def order_value
    total_price = 0
    sale_items.each do |item|
      total_price += item.amount
    end
    return total_price
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :find_sale, only: [:show, :edit, :update, :destroy]

  def index
    @sales = Sale.includes(:sale_items).order_by_sale_date
  end

  def show
    @sale_items = @sale.sale_items.includes({ product: [:uom, :brand, :category] })

    respond_to do |format|
      format.html
      format.pdf do
        pdf = InvoicePdf.new(@sale, @sale.sale_items)
        send_data pdf.render, filename: "Invoice #{1000 + @sale.id}", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def new
    @sale = Sale.new
    sale_items = @sale.sale_items.build
  end

  def create
    @sale = Sale.new(sale_params)

    if @sale.sale_items.blank?
      flash.now[:danger] = "Please enter atleast one sale item"
      render "new"
      return
    end

    if @sale.save
      flash[:success] = "Sale data added successfully"
      redirect_to sales_path
    else
      flash.now[:danger] = "Sale failed"
      render "new"
    end
  end

  def edit
  end

  def update
    sale_items_empty_flag = 1
    sale_params[:sale_items_attributes].keys.each do |key|
      if sale_params[:sale_items_attributes][key]["_destroy"] == "false"
        sale_items_empty_flag = 0
      end
    end

    if sale_items_empty_flag == 1
      flash.now[:danger] = "Please keep atleast one sale item"
      render "edit"
      return
    end

    if @sale.update_attributes(sale_params)
      flash[:success] = "Sale edited Successfully"
      redirect_to sales_path
    else
      flash.now[:danger] = "Error while editing sale"
      render "edit"
    end
  end

  def destroy
    @sale.destroy
    flash[:success] = "Sale Data Successfully Deleted"
    redirect_to sales_path
  end

  private

  def sale_params
    params.require(:sale).permit(:date, sale_items_attributes: [:id, :product_id, :quantity, :rate, :_destroy])
  end

  def find_sale
    @sale = Sale.find(params[:id])
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_sale_item_fields.html.erb
<fieldset class="form-group form-inline border p-2">
  <%= f.collection_select :product_id, Product.active_products, :id, :name, { required: true, prompt: "-- Select Product --" }, class: "form-control mb-2 mr-sm-3" %>
  <%= f.number_field :quantity, placeholder: "Enter Quantity", required: true, class: "form-control mb-2 mr-sm-3" %>
  <%= f.number_field :rate, step: :any, placeholder: "Enter Rate", required: true, class: "form-control mb-2 mr-sm-3" %>
  <%= f.hidden_field :_destroy %>
  <%= link_to ('<i class="fa fa-trash"></i>').html_safe, "#", class: "remove_fields" %>
</fieldset>

app/views/sales/_sales_form.html.erb
<%= form_for @sale do |f| %>

  <% if @sale.errors.any? %>
    <% count = 1%>
    <% @sale.errors.full_messages.each do |msg| %>
      <p class="text-danger"><%= count%>. <%= msg %></p>
      <% count += 1 %>
    <% end %>
  <%end%>

  <div class="form-group form-inline">
    <%= f.label :date, "Date", class: "control-label col-sm-1"%>
    <%= f.text_field :date, onkeydown: "event.preventDefault()", required: true, class: "form-control datepicker" %>
  </div>

  <%= f.fields_for :sale_items do |builder| %>
    <%= render "sale_item_fields", f: builder %>
  <% end %>

  <div>
    <%= link_to_add_fields '<i class="fa fa-plus "></i> Add item'.html_safe, f, :sale_items %><br>
    <%= f.submit class: "btn btn-success mt-3 pull-left", disabled_with: "Saving..." %>
  </div>

<% end %>

app/views/sales/edit.html.erb
<h1 class="text-center mb-5 mt-3">Edit Sale</h1>

<div class="row justify-content-center">
  <div class="col-8">
    <%= render "sales_form" %>
  </div>
</div>

app/views/sales/index.html.erb
<div class="mb-4 mt-2 clearfix">
  <h1 class="d-inline-block mb-0">Sales</h1>
  <%= link_to '<i class="fa fa-plus"></i> Add new sale'.html_safe, new_sale_path, class: "pull-right" %>
</div>
<table class="table table-striped text-center ml-auto mr-auto">
  <thead>
    <tr class="thead-dark">
      <th scope="col">Sale ID</th>
      <th scope="col">Date</th>
      <th scope="col">Order Value</th>
      <th scope="col">Show</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <th scope="row"><%= 1000+sale.id %></th>
        <td><%= sale.date.strftime("%d/%m/%Y") %></td>
        <td><%= number_with_precision(sale.order_value, precision: 2) %></td>
        <td><%= link_to ('<i class="fa fa-eye"></i>').html_safe, sale_path(sale) %></td>
        <td><%= link_to ('<i class="fa fa-edit"></i>').html_safe, edit_sale_path(sale) %></td>
        <td><%= delete_link(sale_path(sale)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/new.html.erb
<h1 class="text-center mb-5 mt-3">New Sale</h1>

<div class="row justify-content-center">
  <div class="col-8">
    <%= render "sales_form" %>
  </div>
</div>

app/views/sales/show.html.erb
<div class="mb-4 mt-2 clearfix text-center">
  <h1 class="d-inline-block mb-0">Show Sale</h1>
  <%= link_to ('<i class="fa fa-edit "></i>').html_safe, edit_sale_path(@sale), class: "pull-right" %>
  <%= delete_link(sale_path(@sale), "pull-right mr-3 ml-3") %>
  <%= link_to ('<i class="fa fa-download "></i>').html_safe, sale_path(@sale, format: :pdf), class: "pull-right" %>
</div>
<div class = "sale-details" >
  <div class="row mt-2 mb-2">
    <div class="col-6">
      <span>Date: <%= @sale.date.strftime("%d/%m/%Y")  %></span>
    </div>
    <div class="col-4">
      <span class="pull-right">Sale ID: </span><br>
      <span class="pull-right">Order Value: </span>
    </div>
    <div class="col-2">
      <span class="pull-left"><%= 1000 + @sale.id %></span><br>
      <span class="pull-left"><%= @sale.order_value %></span>
    </div>
  </div>
  <table class="table table-striped text-center">
    <thead>
      <tr class="thead-dark">
        <th scope="col">S.No</th>
        <th scope="col">Product Name</th>
        <th scope="col">Category</th>
        <th scope="col">Brand</th>
        <th scope="col">UOM</th>
        <th scope="col">Quantity</th>
        <th scope="col">Rate</th>
        <th scope="col">Amount</th>
      </tr>
    </thead>
    <tbody>
      <% serial_number = 1 %>
      <% @sale_items.each do |item| %>
        <tr>
          <th scope="row"><%= serial_number %></th>
          <td><%= item.product.name %></td>
          <td><%= item.product.category.name %></td>
          <td><%= item.product.brand.name %></td>
          <td><%= item.product.uom.abbreviation %></td>
          <td><%= item.quantity %></td>
          <td><%= item.rate %></td>
          <td><%= item.amount %></td>
        </tr>
        <% serial_number += 1 %>
      <% end %>
    </tbody>
  </table>
</div>