config/routes.rb
Rails.application.routes.draw do

  resources :brands, except: [:show, :destroy]
  resources :categories, except: [:show, :destroy]
  resources :uoms, except: [:show, :destroy]
  resources :products, except: [:show, :destroy]
  resources :purchases
  resources :sales
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :active, inclusion: { in: [ true, false ] }

  scope :active_brands, ->{ where(active: true) }
end

app/models/category.rb
class Category < ApplicationRecord

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :active, inclusion: { in: [ true, false ] }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :category
  belongs_to :uom

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :active, inclusion: { in: [ true, false ] }

  scope :active_products, ->{ where(active: true) }
end

app/models/purchase.rb
class Purchase < ApplicationRecord

  has_many :purchase_items, dependent: :destroy
  accepts_nested_attributes_for :purchase_items, reject_if: :all_blank, allow_destroy: true

  scope :order_by_purchase_date, -> { order(date: :desc, id: :desc) }

  def order_value
    total_price = 0
    purchase_items.each do |item|
      total_price += item.amount
    end
    return total_price
  end
end

app/models/purchase_item.rb
class PurchaseItem < ApplicationRecord
  belongs_to :product
  belongs_to :purchase

  validates :quantity, :rate, presence: true

  def amount
    return quantity * rate
  end
end

app/models/sale.rb
class Sale < ApplicationRecord
  has_many :sale_items, dependent: :destroy
  accepts_nested_attributes_for :sale_items, reject_if: :all_blank, allow_destroy: true

  scope :order_by_sale_date, -> { order(date: :desc, id: :desc) }

  def order_value
    total_price = 0
    sale_items.each do |item|
      total_price += item.amount
    end
    return total_price
  end
end

app/models/sale_item.rb
class SaleItem < ApplicationRecord
  belongs_to :product
  belongs_to :sale

  validates :quantity, :rate, presence: true

  def amount
    return quantity * rate
  end
end

app/models/uom.rb
class Uom < ApplicationRecord

  validates :name, :abbreviation, presence: true, uniqueness: { case_sensitive: false }
  validates :active, inclusion: { in: [ true, false ] }

  scope :active_uoms, ->{ where(active: true) }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :find_sale, only: [:show, :edit, :update, :destroy]

  def index
    @sales = Sale.includes(:sale_items).order_by_sale_date
  end

  def show
    @sale_items = @sale.sale_items.includes({ product: [:uom, :brand, :category] })

    respond_to do |format|
      format.html
      format.pdf do
        pdf = InvoicePdf.new(@sale, @sale.sale_items)
        send_data pdf.render, filename: "Invoice #{1000 + @sale.id}", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def new
    @sale = Sale.new
    sale_items = @sale.sale_items.build
  end

  def create
    @sale = Sale.new(sale_params)

    if @sale.sale_items.blank?
      flash.now[:danger] = "Please enter atleast one sale item"
      render "new"
      return
    end

    if @sale.save
      flash[:success] = "Sale data added successfully"
      redirect_to sales_path
    else
      flash.now[:danger] = "Sale failed"
      render "new"
    end
  end

  def edit
  end

  def update
    sale_items_empty_flag = 1
    sale_params[:sale_items_attributes].keys.each do |key|
      if sale_params[:sale_items_attributes][key]["_destroy"] == "false"
        sale_items_empty_flag = 0
      end
    end

    if sale_items_empty_flag == 1
      flash.now[:danger] = "Please keep atleast one sale item"
      render "edit"
      return
    end

    if @sale.update_attributes(sale_params)
      flash[:success] = "Sale edited Successfully"
      redirect_to sales_path
    else
      flash.now[:danger] = "Error while editing sale"
      render "edit"
    end
  end

  def destroy
    @sale.destroy
    flash[:success] = "Sale Data Successfully Deleted"
    redirect_to sales_path
  end

  private

  def sale_params
    params.require(:sale).permit(:date, sale_items_attributes: [:id, :product_id, :quantity, :rate, :_destroy])
  end

  def find_sale
    @sale = Sale.find(params[:id])
  end
end

app/controllers/uoms_controller.rb
class UomsController < ApplicationController

  before_action :find_uom, only: [:edit, :update]

  def index
    @uoms = Uom.all
  end

  def new
    @uom = Uom.new
  end

  def create
    @uom = Uom.new(uom_params)

    if @uom.save
      flash[:success] = "Unit Of Measurement Added Successfully"
      redirect_to uoms_path
    else
      flash.now[:danger] = "Error while adding Unit Of Measurement"
      render "new"
    end
  end

  def edit
  end

  def update
    if @uom.update(uom_params)
      flash[:success] = "Unit Of Measurement edited Successfully"
      redirect_to uoms_path
    else
      flash.now[:danger] = "Error while editing Unit Of Measurement"
      render "new"
    end
  end

  private

  def uom_params
    params.require(:uom).permit(:name, :abbreviation, :active)
  end

  def find_uom
    @uom = Uom.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f:builder)
    end
    link_to(name, "#", class: "add_fields", data: {id: id, fields: fields.gsub("/n","")})
  end

  def delete_link(path, class_name="")
    link_to ('<i class="fa fa-trash " title="Delete Details"></i>').html_safe,
              path,
              method: :delete,
              data: { confirm: "Are you sure?" },
              class: class_name
  end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/uoms_helper.rb
module UomsHelper
end

app/views/layouts/_alerts.html.erb
<% if flash.present? %>
  <div class = "alert-box mt-3">
    <% flash.each do |key, value|%>
      <div class="alert alert-<%= key %> alert-dismissible fade show">
        <strong><%= value %></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Invoice</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Menu
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= categories_path %>">Categories</a>
          <a class="dropdown-item" href="<%= brands_path %>">Brands</a>
          <a class="dropdown-item" href="<%= uoms_path %>">UOM</a>
          <a class="dropdown-item" href="<%= products_path %>">Products</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="<%= purchases_path %>">Purchases</a>
          <a class="dropdown-item" href="<%= sales_path %>">Sales</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invoice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"%>
     <%= javascript_include_tag "https://code.jquery.com/jquery-3.3.1.slim.min.js"%>
    <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" %>
    <%= javascript_include_tag "https://code.jquery.com/jquery-3.2.1.min.js" %>
     <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <%= render "layouts/navbar"%>
    </header>
    <main class="container">
      <%= render "layouts/alerts"%>
      <%= yield %>
    </main>
  </body>
</html>